package com.enb.POJO;
// Generated Aug 23, 2013 11:30:59 PM by Hibernate Tools 3.2.1.GA



/**
 * Deliverablestatus generated by hbm2java
 * <p>
 * Description- Deliverablestatus class is an entity class which stores persistent information of Deliverables
 * </p>
 */
public class Deliverablestatus  implements java.io.Serializable {


     private DeliverablestatusId id;
     private Enbdesc enbdesc;
     private String deliverables;
     private String planToAccomplish;
     private String actualAccomplished;
     private String size;
     private String effort;

    /**
     * constructor- Deliverablestatus
     * default constructor which performs nothing
     */
     public Deliverablestatus() {
    }

    /**
     * constructor- Deliverablestatus
     * it is used to assign id and enbdesc to the deliverable status
     * @param id
     * @param enbdesc 
     */ 
    public Deliverablestatus(DeliverablestatusId id, Enbdesc enbdesc) {
        this.id = id;
        this.enbdesc = enbdesc;
    }
    /**
     * constructor- Deliverablestatus
     * 
     * @param id- reference to the the deliverablestatus
     * @param enbdesc- reference to the ENB
     * @param deliverables
     * @param planToAccomplish
     * @param actualAccomplished
     * @param size
     * @param effort 
     */
    public Deliverablestatus(DeliverablestatusId id, Enbdesc enbdesc, String deliverables, String planToAccomplish, String actualAccomplished, String size, String effort) {
       this.id = id;
       this.enbdesc = enbdesc;
       this.deliverables = deliverables;
       this.planToAccomplish = planToAccomplish;
       this.actualAccomplished = actualAccomplished;
       this.size = size;
       this.effort = effort;
    }
   /*
    * getter and setter methods are generated to perform operations on the deliverablestatus class
    */
    public DeliverablestatusId getId() {
        return this.id;
    }
    
    public void setId(DeliverablestatusId id) {
        this.id = id;
    }
    public Enbdesc getEnbdesc() {
        return this.enbdesc;
    }
    
    public void setEnbdesc(Enbdesc enbdesc) {
        this.enbdesc = enbdesc;
    }
    public String getDeliverables() {
        return this.deliverables;
    }
    
    public void setDeliverables(String deliverables) {
        this.deliverables = deliverables;
    }
    public String getPlanToAccomplish() {
        return this.planToAccomplish;
    }
    
    public void setPlanToAccomplish(String planToAccomplish) {
        this.planToAccomplish = planToAccomplish;
    }
    public String getActualAccomplished() {
        return this.actualAccomplished;
    }
    
    public void setActualAccomplished(String actualAccomplished) {
        this.actualAccomplished = actualAccomplished;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public String getEffort() {
        return this.effort;
    }
    
    public void setEffort(String effort) {
        this.effort = effort;
    }




}


