package com.enb.POJO;
// Generated Aug 27, 2013 12:09:44 PM by Hibernate Tools 3.2.1.GA



/**
 * Deliverablestatus generated by hbm2java
 */
public class Deliverablestatus  implements java.io.Serializable {


     private DeliverablestatusId id;
     private Enbdesc enbdesc;
     private String deliverables;
     private String planToAccomplish;
     private String actualAccomplished;
     private String size;
     private String effort;

    public Deliverablestatus() {
    }

	
    public Deliverablestatus(DeliverablestatusId id, Enbdesc enbdesc) {
        this.id = id;
        this.enbdesc = enbdesc;
    }
    public Deliverablestatus(DeliverablestatusId id, Enbdesc enbdesc, String deliverables, String planToAccomplish, String actualAccomplished, String size, String effort) {
       this.id = id;
       this.enbdesc = enbdesc;
       this.deliverables = deliverables;
       this.planToAccomplish = planToAccomplish;
       this.actualAccomplished = actualAccomplished;
       this.size = size;
       this.effort = effort;
    }
   
    public DeliverablestatusId getId() {
        return this.id;
    }
    
    public void setId(DeliverablestatusId id) {
        this.id = id;
    }
    public Enbdesc getEnbdesc() {
        return this.enbdesc;
    }
    
    public void setEnbdesc(Enbdesc enbdesc) {
        this.enbdesc = enbdesc;
    }
    public String getDeliverables() {
        return this.deliverables;
    }
    
    public void setDeliverables(String deliverables) {
        this.deliverables = deliverables;
    }
    public String getPlanToAccomplish() {
        return this.planToAccomplish;
    }
    
    public void setPlanToAccomplish(String planToAccomplish) {
        this.planToAccomplish = planToAccomplish;
    }
    public String getActualAccomplished() {
        return this.actualAccomplished;
    }
    
    public void setActualAccomplished(String actualAccomplished) {
        this.actualAccomplished = actualAccomplished;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public String getEffort() {
        return this.effort;
    }
    
    public void setEffort(String effort) {
        this.effort = effort;
    }




}


