package com.enb.POJO;
// Generated Aug 23, 2013 11:30:59 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Enbdesc generated by hbm2java
 * <p>
 * Description- Enbdesc class is an entity class which stores persistent information of ENB
 * </p>
 */

public class Enbdesc  implements java.io.Serializable {

     private Integer id;
     private Userauth userauth;
     private Project project;
     private Date fromdate;
     private Date todate;
     private String enbname;
     private Set noteses = new HashSet(0);  // add notes to set
     private Set plans = new HashSet(0);    // add plans to set
     private Set deliverablestatuses = new HashSet(0);  // add deliverablestatuses to set
     private Set lessonses = new HashSet(0);    // add lessonses to set

    public Enbdesc() {
    }
    /**
     * 
     * @param userauth- user authentication reference to access the user authentication
     * @param project- project reference to access project
     * @param fromdate
     * @param todate
     * @param enbname
     * @param noteses- set of objects of notes type
     * @param plans- set of objects of plan type
     * @param deliverablestatuses- set of objects of deliverable type
     * @param lessonses- set of objects of lessons type 
     */
    public Enbdesc(Userauth userauth, Project project, Date fromdate, Date todate, String enbname, Set noteses, Set plans, Set deliverablestatuses, Set lessonses) {
       this.userauth = userauth;
       this.project = project;
       this.fromdate = fromdate;
       this.todate = todate;
       this.enbname = enbname;
       this.noteses = noteses;  
       this.plans = plans;
       this.deliverablestatuses = deliverablestatuses;
       this.lessonses = lessonses;
    }
     /*
    * getter and setter methods are generated to perform operations on the enbdesc class
    */
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Userauth getUserauth() {
        return this.userauth;
    }
    
    public void setUserauth(Userauth userauth) {
        this.userauth = userauth;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public Date getFromdate() {
        return this.fromdate;
    }
    
    public void setFromdate(Date fromdate) {
        this.fromdate = fromdate;
    }
    public Date getTodate() {
        return this.todate;
    }
    
    public void setTodate(Date todate) {
        this.todate = todate;
    }
    public String getEnbname() {
        return this.enbname;
    }
    
    public void setEnbname(String enbname) {
        this.enbname = enbname;
    }
    public Set getNoteses() {
        return this.noteses;
    }
    
    public void setNoteses(Set noteses) {
        this.noteses = noteses;
    }
    public Set getPlans() {
        return this.plans;
    }
    
    public void setPlans(Set plans) {
        this.plans = plans;
    }
    public Set getDeliverablestatuses() {
        return this.deliverablestatuses;
    }
    
    public void setDeliverablestatuses(Set deliverablestatuses) {
        this.deliverablestatuses = deliverablestatuses;
    }
    public Set getLessonses() {
        return this.lessonses;
    }
    
    public void setLessonses(Set lessonses) {
        this.lessonses = lessonses;
    }




}


