package com.enb.POJO;
// Generated Sep 24, 2013 10:52:21 AM by Hibernate Tools 3.2.1.GA



/**
 * Groups generated by hbm2java
 */
public class Groups  implements java.io.Serializable {


     private Integer id;
     private Userauth userauthByMid;
     private Userauth userauthBySid;

    public Groups() {
    }

    public Groups(Userauth userauthByMid, Userauth userauthBySid) {
       this.userauthByMid = userauthByMid;
       this.userauthBySid = userauthBySid;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Userauth getUserauthByMid() {
        return this.userauthByMid;
    }
    
    public void setUserauthByMid(Userauth userauthByMid) {
        this.userauthByMid = userauthByMid;
    }
    public Userauth getUserauthBySid() {
        return this.userauthBySid;
    }
    
    public void setUserauthBySid(Userauth userauthBySid) {
        this.userauthBySid = userauthBySid;
    }




}


