package com.enb.POJO;
// Generated Sep 24, 2013 10:52:21 AM by Hibernate Tools 3.2.1.GA



/**
 * LessonsId generated by hbm2java
 */
public class LessonsId  implements java.io.Serializable {


     private int enbid;
     private int sno;

    public LessonsId() {
    }

    public LessonsId(int enbid, int sno) {
       this.enbid = enbid;
       this.sno = sno;
    }
   
    public int getEnbid() {
        return this.enbid;
    }
    
    public void setEnbid(int enbid) {
        this.enbid = enbid;
    }
    public int getSno() {
        return this.sno;
    }
    
    public void setSno(int sno) {
        this.sno = sno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LessonsId) ) return false;
		 LessonsId castOther = ( LessonsId ) other; 
         
		 return (this.getEnbid()==castOther.getEnbid())
 && (this.getSno()==castOther.getSno());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEnbid();
         result = 37 * result + this.getSno();
         return result;
   }   


}


