package com.enb.POJO;
// Generated Aug 23, 2013 11:30:59 PM by Hibernate Tools 3.2.1.GA

/**
 * Lessons generated by hbm2java
 * <p>
 * Description- Lessons class is an entity class which stores persistent information of lessons 
 * </p>
 */
public class Lessons  implements java.io.Serializable {
     private LessonsId id;
     private Enbdesc enbdesc;
     private String context;
     private String lessons;
    /* Constructor-Lessons 
     * default constructor */ 
    public Lessons() {
    }
    /**
     * Constructor-Lessons
     * 
     * @param id- id returned from the LessonsId class 
     * @param enbdesc- all details of ENB 
     */
    public Lessons(LessonsId id, Enbdesc enbdesc) {
        this.id = id;
        this.enbdesc = enbdesc;
    }
    /**
     * Constructor-Lessons
     * @param id-  lessons id 
     * @param enbdesc- all details of ENB 
     * @param context- context of lessons
     * @param lessons 
     */
    public Lessons(LessonsId id, Enbdesc enbdesc, String context, String lessons) {
       this.id = id;
       this.enbdesc = enbdesc;
       this.context = context;
       this.lessons = lessons;
    }
   /*
    * getter and setter methods are generated to perform operations on the lessons class
    */
    public LessonsId getId() {
        return this.id;
    }
    
    public void setId(LessonsId id) {
        this.id = id;
    }
    public Enbdesc getEnbdesc() {
        return this.enbdesc;
    }
    
    public void setEnbdesc(Enbdesc enbdesc) {
        this.enbdesc = enbdesc;
    }
    public String getContext() {
        return this.context;
    }
    
    public void setContext(String context) {
        this.context = context;
    }
    public String getLessons() {
        return this.lessons;
    }
    
    public void setLessons(String lessons) {
        this.lessons = lessons;
    }




}


