package com.enb.POJO;
// Generated Sep 24, 2013 10:52:21 AM by Hibernate Tools 3.2.1.GA



/**
 * Lessons generated by hbm2java
 */
public class Lessons  implements java.io.Serializable {


     private LessonsId id;
     private Enbdesc enbdesc;
     private String context;
     private String lessons;

    public Lessons() {
    }

	
    public Lessons(LessonsId id, Enbdesc enbdesc) {
        this.id = id;
        this.enbdesc = enbdesc;
    }
    public Lessons(LessonsId id, Enbdesc enbdesc, String context, String lessons) {
       this.id = id;
       this.enbdesc = enbdesc;
       this.context = context;
       this.lessons = lessons;
    }
   
    public LessonsId getId() {
        return this.id;
    }
    
    public void setId(LessonsId id) {
        this.id = id;
    }
    public Enbdesc getEnbdesc() {
        return this.enbdesc;
    }
    
    public void setEnbdesc(Enbdesc enbdesc) {
        this.enbdesc = enbdesc;
    }
    public String getContext() {
        return this.context;
    }
    
    public void setContext(String context) {
        this.context = context;
    }
    public String getLessons() {
        return this.lessons;
    }
    
    public void setLessons(String lessons) {
        this.lessons = lessons;
    }




}


