package com.enb.POJO;
// Generated Aug 23, 2013 11:30:59 PM by Hibernate Tools 3.2.1.GA



/**
 * Notes generated by hbm2java
 * <p>
 * Description- Notes class is an entity class which stores persistent information of Notes 
 * </p>
 */

public class Notes  implements java.io.Serializable {

     
     private int enbid;             //enb id to open enb to write notes
     private Enbdesc enbdesc;       //reference to ENB
     private byte[] notes;          //store content in notes

   /**
    * Constructor- Notes
    * default constructor
    */
     public Notes() {
    }
    /**
     * Constructor- Notes
     * <p>
     * Description- used to assign the given values to the ENB
     * @param enbid
     * @param enbdesc-  reference to access ENB 
     */ 
    public Notes(int enbid, Enbdesc enbdesc) {
        this.enbid = enbid;
        this.enbdesc = enbdesc;
    }
    /**
     * Constructor- Notes
     * <p>
     * Description- used to write notes to the ENB 
     * </p>
     * 
     * @param enbid
     * @param enbdesc- enbdesc reference to access ENB
     * @param notes- used to store notes 
     */
    public Notes(int enbid, Enbdesc enbdesc, byte[] notes) {
       this.enbid = enbid;
       this.enbdesc = enbdesc;
       this.notes = notes;
    }
   /*
    * getter and setter methods are generated to perform operations on the notes class
    */
    public int getEnbid() {
        return this.enbid;
    }
    
    public void setEnbid(int enbid) {
        this.enbid = enbid;
    }
    public Enbdesc getEnbdesc() {
        return this.enbdesc;
    }
    
    public void setEnbdesc(Enbdesc enbdesc) {
        this.enbdesc = enbdesc;
    }
    public byte[] getNotes() {
        return this.notes;
    }
    
    public void setNotes(byte[] notes) {
        this.notes = notes;
    }




}


