package com.enb.POJO;
// Generated Aug 23, 2013 11:30:59 PM by Hibernate Tools 3.2.1.GA



/**
 * Plan generated by hbm2java
 * <p>
 * Description- Plan class is an entity class which stores persistent information of plan 
 * </p>
 */
public class Plan  implements java.io.Serializable {


     private PlanId id;
     private Enbdesc enbdesc;
     private String deliverable;
     private String intendToAccomplish;
    /**
     * constructor- Plan
     * default constructor
     */ 
    public Plan() {
    }

    /**
     * constructor- Plan
     * <p>
     * Description- used to assign plan id and ENB description to plan 
     * </p>
     * @param id
     * @param enbdesc 
     */
    public Plan(PlanId id, Enbdesc enbdesc) {
        this.id = id;
        this.enbdesc = enbdesc;
    }
    /**
     * constructor- Plan
     * used to assign the given parameters
     * @param id- reference to access plan class
     * @param enbdesc- reference to access ENB
     * @param deliverable
     * @param intendToAccomplish 
     */
    public Plan(PlanId id, Enbdesc enbdesc, String deliverable, String intendToAccomplish) {
       this.id = id;
       this.enbdesc = enbdesc;
       this.deliverable = deliverable;
       this.intendToAccomplish = intendToAccomplish;
    }
   /*
    * getter and setter methods are generated to perform operations on the plan class
    */
    public PlanId getId() {
        return this.id;
    }
    
    public void setId(PlanId id) {
        this.id = id;
    }
    public Enbdesc getEnbdesc() {
        return this.enbdesc;
    }
    
    public void setEnbdesc(Enbdesc enbdesc) {
        this.enbdesc = enbdesc;
    }
    public String getDeliverable() {
        return this.deliverable;
    }
    
    public void setDeliverable(String deliverable) {
        this.deliverable = deliverable;
    }
    public String getIntendToAccomplish() {
        return this.intendToAccomplish;
    }
    
    public void setIntendToAccomplish(String intendToAccomplish) {
        this.intendToAccomplish = intendToAccomplish;
    }




}


