package com.enb.POJO;
// Generated Sep 24, 2013 10:52:21 AM by Hibernate Tools 3.2.1.GA



/**
 * Plan generated by hbm2java
 */
public class Plan  implements java.io.Serializable {


     private PlanId id;
     private Enbdesc enbdesc;
     private String deliverable;
     private String intendToAccomplish;

    public Plan() {
    }

	
    public Plan(PlanId id, Enbdesc enbdesc) {
        this.id = id;
        this.enbdesc = enbdesc;
    }
    public Plan(PlanId id, Enbdesc enbdesc, String deliverable, String intendToAccomplish) {
       this.id = id;
       this.enbdesc = enbdesc;
       this.deliverable = deliverable;
       this.intendToAccomplish = intendToAccomplish;
    }
   
    public PlanId getId() {
        return this.id;
    }
    
    public void setId(PlanId id) {
        this.id = id;
    }
    public Enbdesc getEnbdesc() {
        return this.enbdesc;
    }
    
    public void setEnbdesc(Enbdesc enbdesc) {
        this.enbdesc = enbdesc;
    }
    public String getDeliverable() {
        return this.deliverable;
    }
    
    public void setDeliverable(String deliverable) {
        this.deliverable = deliverable;
    }
    public String getIntendToAccomplish() {
        return this.intendToAccomplish;
    }
    
    public void setIntendToAccomplish(String intendToAccomplish) {
        this.intendToAccomplish = intendToAccomplish;
    }




}


