package com.enb.POJO;
// Generated Aug 23, 2013 11:30:59 PM by Hibernate Tools 3.2.1.GA



/**
 * PlanId generated by hbm2java
 * Description- PlanId is an entity class used to generate id for plans based on the enbid 
 */
public class PlanId  implements java.io.Serializable {


     private int enbid;
     private int sno;

    public PlanId() {
    }

    public PlanId(int enbid, int sno) {
       this.enbid = enbid;
       this.sno = sno;
    }
   
    public int getEnbid() {
        return this.enbid;
    }
    
    public void setEnbid(int enbid) {
        this.enbid = enbid;
    }
    public int getSno() {
        return this.sno;
    }
    
    public void setSno(int sno) {
        this.sno = sno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlanId) ) return false;
		 PlanId castOther = ( PlanId ) other; 
         
		 return (this.getEnbid()==castOther.getEnbid())
 && (this.getSno()==castOther.getSno());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEnbid();
         result = 37 * result + this.getSno();
         return result;   //return random value as result
   }   


}


