package com.enb.POJO;
// Generated Aug 19, 2013 3:22:20 PM by Hibernate Tools 3.2.1.GA



/**
 * Plan generated by hbm2java
 */
public class Plan  implements java.io.Serializable {


     private Integer id;
     private Enbdesc enbdesc;
     private String deliverable;
     private String intendToAccomplish;

    public Plan() {
    }

    public Plan(Enbdesc enbdesc, String deliverable, String intendToAccomplish) {
       this.enbdesc = enbdesc;
       this.deliverable = deliverable;
       this.intendToAccomplish = intendToAccomplish;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Enbdesc getEnbdesc() {
        return this.enbdesc;
    }
    
    public void setEnbdesc(Enbdesc enbdesc) {
        this.enbdesc = enbdesc;
    }
    public String getDeliverable() {
        return this.deliverable;
    }
    
    public void setDeliverable(String deliverable) {
        this.deliverable = deliverable;
    }
    public String getIntendToAccomplish() {
        return this.intendToAccomplish;
    }
    
    public void setIntendToAccomplish(String intendToAccomplish) {
        this.intendToAccomplish = intendToAccomplish;
    }




}


