package com.enb.POJO;
// Generated Aug 19, 2013 3:22:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project  implements java.io.Serializable {


     private int id;
     private Userauth userauth;
     private String projectName;
     private Date from;
     private Date to;
     private Set enbdescs = new HashSet(0);

    public Project() {
    }

	
    public Project(int id) {
        this.id = id;
    }
    public Project(int id, Userauth userauth, String projectName, Date from, Date to, Set enbdescs) {
       this.id = id;
       this.userauth = userauth;
       this.projectName = projectName;
       this.from = from;
       this.to = to;
       this.enbdescs = enbdescs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Userauth getUserauth() {
        return this.userauth;
    }
    
    public void setUserauth(Userauth userauth) {
        this.userauth = userauth;
    }
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    public Date getFrom() {
        return this.from;
    }
    
    public void setFrom(Date from) {
        this.from = from;
    }
    public Date getTo() {
        return this.to;
    }
    
    public void setTo(Date to) {
        this.to = to;
    }
    public Set getEnbdescs() {
        return this.enbdescs;
    }
    
    public void setEnbdescs(Set enbdescs) {
        this.enbdescs = enbdescs;
    }




}


