package com.enb.POJO;
// Generated Aug 20, 2013 2:06:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project  implements java.io.Serializable {


     private int id;
     private Userauth userauth;
     private String projectName;
     private Date fromDate;
     private Date toDate;
     private Set enbdescs = new HashSet(0);
     private Set enbdescs_1 = new HashSet(0);

    public Project() {
    }

	
    public Project(int id) {
        this.id = id;
    }
    public Project(int id, Userauth userauth, String projectName, Date fromDate, Date toDate, Set enbdescs, Set enbdescs_1) {
       this.id = id;
       this.userauth = userauth;
       this.projectName = projectName;
       this.fromDate = fromDate;
       this.toDate = toDate;
       this.enbdescs = enbdescs;
       this.enbdescs_1 = enbdescs_1;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Userauth getUserauth() {
        return this.userauth;
    }
    
    public void setUserauth(Userauth userauth) {
        this.userauth = userauth;
    }
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    public Date getToDate() {
        return this.toDate;
    }
    
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }
    public Set getEnbdescs() {
        return this.enbdescs;
    }
    
    public void setEnbdescs(Set enbdescs) {
        this.enbdescs = enbdescs;
    }
    public Set getEnbdescs_1() {
        return this.enbdescs_1;
    }
    
    public void setEnbdescs_1(Set enbdescs_1) {
        this.enbdescs_1 = enbdescs_1;
    }




}


