package com.enb.POJO;
// Generated Aug 23, 2013 11:30:59 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Userlog generated by hbm2java
 * <p>
 * Description- Userlog class is an entity class which stores persistent information of all the activities of a user 
 * </p>
 */
public class Userlog  implements java.io.Serializable {


     private Integer id;
     private String uid;
     private Date logDt;
     private String description;
    /*
     * constructor- Userlog
     * default constructor
     */
    public Userlog() {
    }
    /**
     * constructor- Userlog
     *<p>
     * Description- used to display the user activities based on the user id and date
     * </p>
     * 
     * @param uid
     * @param logDt
     * @param description 
     */
    public Userlog(String uid, Date logDt, String description) {
       this.uid = uid;
       this.logDt = logDt;
       this.description = description;
    }
    /*
    * getter and setter methods are generated to perform operations on the usrlog class
    * */
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    public Date getLogDt() {
        return this.logDt;
    }
    
    public void setLogDt(Date logDt) {
        this.logDt = logDt;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


