package com.enb.POJO;
// Generated Aug 22, 2013 12:32:00 AM by Hibernate Tools 3.2.1.GA



/**
 * Userlog generated by hbm2java
 */
public class Userlog  implements java.io.Serializable {


     private UserlogId id;
     private String description;

    public Userlog() {
    }

	
    public Userlog(UserlogId id) {
        this.id = id;
    }
    public Userlog(UserlogId id, String description) {
       this.id = id;
       this.description = description;
    }
   
    public UserlogId getId() {
        return this.id;
    }
    
    public void setId(UserlogId id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


