package com.enb.POJO;
// Generated Aug 19, 2013 6:07:04 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Userauth generated by hbm2java
 */
public class Userauth  implements java.io.Serializable {


     private Integer id;
     private String emailId;
     private String password;
     private String name;
     private String verificationCode;
     private Set enbdescs = new HashSet(0);
     private Set userlogs = new HashSet(0);
     private Set projects = new HashSet(0);

    public Userauth() {
    }

    public Userauth(String emailId, String password, String name, String verificationCode, Set enbdescs, Set userlogs, Set projects) {
       this.emailId = emailId;
       this.password = password;
       this.name = name;
       this.verificationCode = verificationCode;
       this.enbdescs = enbdescs;
       this.userlogs = userlogs;
       this.projects = projects;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getVerificationCode() {
        return this.verificationCode;
    }
    
    public void setVerificationCode(String verificationCode) {
        this.verificationCode = verificationCode;
    }
    public Set getEnbdescs() {
        return this.enbdescs;
    }
    
    public void setEnbdescs(Set enbdescs) {
        this.enbdescs = enbdescs;
    }
    public Set getUserlogs() {
        return this.userlogs;
    }
    
    public void setUserlogs(Set userlogs) {
        this.userlogs = userlogs;
    }
    public Set getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set projects) {
        this.projects = projects;
    }




}


