package com.enb.POJO;
// Generated Aug 27, 2013 12:09:44 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Userlog generated by hbm2java
 */
public class Userlog  implements java.io.Serializable {


     private Integer id;
     private String uid;
     private Date logDt;
     private String description;

    public Userlog() {
    }

    public Userlog(String uid, Date logDt, String description) {
       this.uid = uid;
       this.logDt = logDt;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    public Date getLogDt() {
        return this.logDt;
    }
    
    public void setLogDt(Date logDt) {
        this.logDt = logDt;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


